# Generated by Django 5.2.5 on 2025-08-11 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app.producto'),
        ),
    ]
